replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app:
  env:
  envName:
service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: https://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 5000
  internalPort: 5000
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
livenessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
postgresql:
  enabled: true
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

# workers:
#   worker:
#     replicaCount: 1
#     terminationGracePeriodSeconds: 60
#     command: ["bundle", "exec", "sidekiq", "-c", "2"]
#     preStopCommand: ["/bin/bash", "-l", "-c", "cd /opt/myapp/current; for f in tmp/pids/sidekiq*.pid; do bundle exec sidekiqctl stop $f; done"]
#     livenessProbe:
#       path: "/_sidebeat"
#       initialDelaySeconds: 15
#       timeoutSeconds: 15
#       scheme: "HTTP"
#     readinessProbe:
#       path: "/_sidebeat"
#       initialDelaySeconds: 15
#       timeoutSeconds: 15
#       scheme: "HTTP"
