AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: No

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - spec/**/*
