name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  batch: false
  branches:
    include: [ master ]
jobs:
- job: build
  displayName: 'Build'
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'
  - script: ./scripts/cibuild.sh
    displayName: 'CI Build'
- job: test
  displayName: 'Test'
  dependsOn: build
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: ls
    displayName: 'Temp Test'
- job: release
  displayName: 'Release'
  dependsOn: test
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: ./scripts/heroku_release.sh whiz-store ${HEROKU_API_KEY}
    displayName: 'Temp Release'
