version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  RAILS_ENV: development
  NODE_ENV: development
  ENVIRONMENT_NAME: development
  ENVIRONMENT_URL: http://signjunkie.mythcoders.dev
  PAYMENT_ENV: sandbox
  STORAGE_BUCKET: none
  REDIS_URL: redis://myth-redis:6379/2
  REDIS_NAMESPACE: sign-junkie-dev
  HERMES_API_KEY: key
  HERMES_API_SECRET: secret

services:
  app:
    image: sign-junkie
    command: ['sh', './bin/dev']
    build:
      context: .
      target: base
    container_name: sign-junkie-app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:signjunkie.mythcoders.dev"
    volumes:
      - .:/opt/sign-junkie
    environment:
      <<: *shared-environment-variables
    stdin_open: true
    tty: true

  worker:
    image: sign-junkie
    container_name: sign-junkie-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - .:/opt/sign-junkie
    environment:
      <<: *shared-environment-variables
    depends_on:
      - app

networks:
  default:
    name: mythcoders_dev
    external: true
