version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  RAILS_ENV: development
  NODE_ENV: development
  ENVIRONMENT_NAME: development
  ENVIRONMENT_URL: http://signjunkie.mythcoders.dev
  PAYMENT_ENV: sandbox
  STORAGE_BUCKET: none
  REDIS_URL: redis://myth-redis:6379/2
  REDIS_NAMESPACE: sign-junkie-dev

services:
  app:
    image: sign-junkie
    command: ["sh", "./scripts/app", "start", "setup"]
    build:
      context: .
      target: base
    container_name: sign-junkie-app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:signjunkie.mythcoders.dev"
    volumes:
      - .:/opt/sign-junkie
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: webpacker
    stdin_open: true
    tty: true

  worker:
    image: sign-junkie
    container_name: sign-junkie-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - .:/opt/sign-junkie
    environment:
      <<: *shared-environment-variables
    depends_on:
      - app

  webpacker:
    image: sign-junkie
    container_name: sign-junkie-webpacker
    command: ["sh", "./scripts/webpack"]
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/opt/sign-junkie

networks:
  default:
    name: mythcoders_dev
    external: true
