version: "3.7"
services:
  app:
    build:
      context: .
      target: base
    container_name: ares-app
    command: ["sh", "./scripts/app", "start", "db:local"]
    labels:
      traefik.frontend.rule: "Host:ares.localhost"
    volumes:
      - ./:/app
    environment:
      RAILS_ENV: development
      GITLAB_ENVIRONMENT_NAME: development
      PAYMENT_ENV: sandbox
      DATABASE_URL: "postgres://postgres:postgres@db:5432/ares_dev"
      STORAGE_BUCKET: none
      REDIS_URL: redis://redis:6379
      REDIS_NAMESPACE: ares-dev
    depends_on:
      - db
      - net
      - redis
    stdin_open: true
    tty: true

  worker:
    image: ares_app:latest
    container_name: ares-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - ./:/app
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379
      REDIS_NAMESPACE: ares-dev
    depends_on:
      - redis
    stdin_open: true
    tty: true

  redis:
    image: redis:5.0.5-alpine
    container_name: ares-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:11.4
    container_name: ares-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata

  net:
    image: traefik:latest
    container_name: ares-net
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata:
