version: '3.7'
services:

  app:
    build:
      context: .
      target: base
      labels:
        com.mythcoders.description: "Ares"
    container_name: ares-app
    command: "bundle exec rails s -b 0.0.0.0 -p 5000"
    labels:
      traefik.frontend.rule: "Host:ares.localhost"
    volumes:
      - "./:/app"
    environment:
      RAILS_ENV: development
      PAYMENT_ENV: sandbox
      DATABASE_URL: "postgres://postgres:postgres@db:5432/ares_dev"
      STORAGE_BUCKET: "mcdoc-dvstg-signjunkie"
    depends_on:
      - db
      - net
    stdin_open: true
    tty: true

  db:
    image: postgres:11.4
    container_name: ares-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata

  net:
    image: traefik:latest
    container_name: ares-net
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: