version: "3.7"

x-shared-environment-variables: &shared-environment-variables
  RAILS_ENV: development
  NODE_ENV: development
  GITLAB_ENVIRONMENT_NAME: development
  GITLAB_ENVIRONMENT_URL: apollo.mythcoders.dev
  PAYMENT_ENV: sandbox
  DATABASE_URL: "postgres://postgres:postgres@myth-psql:5432/apollo_dev"
  STORAGE_BUCKET: none
  REDIS_URL: redis://myth-redis:6379/0
  REDIS_NAMESPACE: apollo-dev
  WORKER_REDIS_NAMESPACE: apollo-worker-dev

services:
  app:
    image: apollo
    command: ["sh", "./scripts/app", "start", "setup"]
    build:
      context: .
      target: base
    container_name: apollo-app
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:apollo.mythcoders.dev"
    volumes:
      - .:/app
      - '/app/node_modules/'
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: webpacker
    stdin_open: true
    tty: true

  webpacker:
    image: apollo
    container_name: apollo-webpacker
    command: ["./bin/webpack-dev-server"]
    environment:
      <<: *shared-environment-variables
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app
      - '/app/node_modules/'
    ports:
      - '5001'
    depends_on:
      - app

  worker:
    image: apollo
    container_name: apollo-worker
    command: ["sh", "./scripts/worker", "start"]
    volumes:
      - .:/app
    environment:
      <<: *shared-environment-variables
    depends_on:
      - app

networks:
  default:
    name: mythcoders_dev
