services:
  - type: web
    name: rails-web
    plan: starter
    env: docker
    region: ohio
    healthCheckPath: /_heartbeat
    envVars:
      - fromGroup: sign-junkie

  - type: worker
    name: sidekiq-worker
    env: docker
    region: ohio
    dockerCommand: ./scripts/worker start
    envVars:
      - fromGroup: sign-junkie

envVarGroups:
  - name: sign-junkie
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CDN_URL
        sync: false
      - key: ENVIRONMENT_NAME
        sync: false
      - key: ENVIRONMENT_URL
        sync: false
      - key: PAYMENT_ENV
        sync: false
      - key: NODE_ENV
        sync: false
      - key: RAILS_ENV
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: 1
      - key: RAILS_SERVE_STATIC_FILES
        value: 1
      - key: REDIS_NAMESPACE
        sync: false
      - key: STORAGE_BUCKET
        sync: false
