replicaCount: 1
hpa:
  enabled: false
ingress:
  tls:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '100m'
extraLabels:
  tags.datadoghq.com/env: 'review'
  tags.datadoghq.com/service: 'hubble'
livenessProbe:
  probeType: 'httpGet'
  path: /_heartbeat
  port: 5000
  initialDelaySeconds: 20
  timeoutSeconds: 15
readinessProbe:
  probeType: 'httpGet'
  path: /_heartbeat
  port: 5000
  initialDelaySeconds: 20
  timeoutSeconds: 15
resources:
  limits:
    memory: 1Gi
    cpu: 800m
  requests:
    memory: 256Mi
    cpu: 200m
workerResources:
  limits:
    memory: 1Gi
    cpu: 800m
  requests:
    memory: 256Mi
    cpu: 200m
podDisruptionBudget:
  enabled: false
workers:
  sidekiq:
    replicaCount: 1
    terminationGracePeriodSeconds: 29
    command: ['sh', './scripts/worker', 'start']
    preStopCommand: ['sh', './scripts/worker', 'stop']
    livenessProbe:
      probeType: 'exec'
      command:
        - cat
        - /opt/hubble/tmp/health_checks/worker
      initialDelaySeconds: 25
      timeoutSeconds: 5
    readinessProbe:
      probeType: 'exec'
      command:
        - cat
        - /opt/hubble/tmp/health_checks/worker
      initialDelaySeconds: 25
      timeoutSeconds: 5