replicaCount: 1
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
ingress:
  tls:
    enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = "www.signjunkieworkshop.com") {
          return 308 https://signjunkieworkshop.com$request_uri;
      }
extraLabels:
  tags.datadoghq.com/env: 'prod'
  tags.datadoghq.com/service: 'sign-junkie'
livenessProbe:
  probeType: 'httpGet'
  path: /_heartbeat
  port: 5000
  initialDelaySeconds: 20
  timeoutSeconds: 15
readinessProbe:
  probeType: 'httpGet'
  path: /_heartbeat
  port: 5000
  initialDelaySeconds: 20
  timeoutSeconds: 15
resources:
  limits:
    memory: 1500Mi
    cpu: 1500m
  requests:
    memory: 512Mi
    cpu: 500m
workerResources:
  limits:
    memory: 2Gi
    cpu: 2000m
  requests:
    memory: 256Mi
    cpu: 250m
podDisruptionBudget:
  enabled: true
#   minAvailable: 2
workers:
  sidekiq:
    replicaCount: 1
    terminationGracePeriodSeconds: 60
    command: ["sh", "./scripts/worker", "start"]
    preStopCommand: ["sh", "./scripts/worker", "stop"]
    livenessProbe:
      probeType: 'exec'
      command:
        - cat
        - /opt/sign-junkie/tmp/health_checks/worker
      initialDelaySeconds: 25
      timeoutSeconds: 5
    readinessProbe:
      probeType: 'exec'
      command:
        - cat
        - /opt/sign-junkie/tmp/health_checks/worker
      initialDelaySeconds: 25
      timeoutSeconds: 5
