replicaCount: 1
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
service:
  externalPort: 5000
  internalPort: 5000
ingress:
  tls:
    enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
livenessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/_heartbeat"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
postgresql:
  enabled: true

podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

workers:
  sidekiq:
    replicaCount: 1
    terminationGracePeriodSeconds: 60
    command: ["sh", "./scripts/worker", "start"]
    preStopCommand: ["sh", "./scripts/worker", "stop"]
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 15
      probeType: "exec"
      command: "stat /app/tmp/pids/sidekiq_started || exit 1"
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 3
      probeType: "exec"
      command: "stat /app/tmp/pids/sidekiq_started || exit 1"
