#!/bin/bash

echo '*** STARTING APOLLO ***'
echo 'Configuring the hyperdrive...'

cd "$(dirname "$0")/.."

if [ "$2" == "setup" ]; then
  echo "Establsihing connection to the databank..."
  ./bin/rails db:exists && ./bin/rails db:migrate VERBOSE=true || ./bin/rails db:setup VERBOSE=true
fi

if [ "$1" == "start" ]; then
  if [ -f "tmp/pids/server.pid" ]; then
    echo "Scans detected server.pid in sector 1 -- neutralizing"
    rm -rf tmp/pids/server.pid
  fi

  echo "Preparing for warp on port ${APP_PORT}..."
  ./bin/rails server -b 0.0.0.0 -p $APP_PORT
fi
