#!/bin/sh

echo '==> Watching js...'
esbuild app/javascript/*.* --bundle --sourcemap \
  --external:@hotwired/stimulus \
  --external:@hotwired/stimulus-loading \
  --external:jquery \
  --external:mapbox-gl \
  --external:trix \
  --outdir=app/assets/builds --watch
