name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      publish: ${{ github.actor != 'dependabot[bot]' }}
    secrets:
      packageToken: ${{ secrets.PACKAGE_TOKEN }}

  linters:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/linters.yaml

  tests:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/tests.yaml
    secrets:
      packageToken: ${{ secrets.PACKAGE_TOKEN }}
      railsMasterKey: ${{ secrets.RAILS_MASTER_KEY }}

  assets:
    if: github.actor != 'dependabot[bot]'
    needs: build
    uses: ./.github/workflows/assets.yaml
    with:
      assetBucket: ${{ github.event_name == 'push' && 'mcdig-pdcdn-sign-junkie' || 'mcdig-tscdn-sign-junkie' }}
    secrets:
      packageToken: ${{ secrets.PACKAGE_TOKEN }}

  deploy:
    if: github.actor != 'dependabot[bot]'
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: ${{ github.event_name == 'push' && 'prod' || 'test' }}
      prNumber: ${{ github.event_name == 'push' && '0' || github.event.pull_request.number }}
