name: linters

on:
  workflow_call:
    secrets:
      packageToken:
        required: true

jobs:
  ruby:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_RUBYGEMS__PKG__GITHUB__COM: ${{ github.actor }}:${{ secrets.packageToken }}
        with:
          bundler-cache: true

      - name: standardrb
        run: ./scripts/ci linter

      - name: brakeman
        continue-on-error: true
        run: |
          gem install brakeman
          ./scripts/ci brakeman

      - name: bundler audit
        run: |
          gem install bundler-audit
          ./scripts/ci audit
