name: manual release

on:
  workflow_dispatch:
    inputs:
      syncAssets:
        description: 'Sync Assets'
        type: boolean
        required: true
        default: false

jobs:
  assets:
    if: github.event.inputs.syncAssets
    uses: ./.github/workflows/assets.yaml
    with:
      assetBucket: mcdig-pdcdn-hubble
    secrets:
      packageToken: ${{ secrets.PACKAGE_TOKEN }}

  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: prod
