name: teardown

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  teardown:
    name: teardown
    runs-on: [self-hosted, test]
    # environment:
    #   name: pr-${{ github.event.pull_request.number }}
    #   url: "https://pr-${{ github.event.pull_request.number }}.test.hubble.vote"
    steps:
      - name: nomad
        env:
          HUBBLE_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: nomad job stop -yes -purge -verbose hubble-pr-$HUBBLE_PR_NUMBER
