name: teardown

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  teardown:
    name: teardown
    runs-on: [self-hosted, test]
    # environment:
    #   name: pr-${{ github.event.pull_request.number }}
    #   url: "https://pr-${{ github.event.pull_request.number }}.test.signjunkieworkshop.com"
    steps:
      - name: nomad
        env:
          SIGN_JUNKIE_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: nomad job stop -yes -purge -verbose sign-junkie-pr-$SIGN_JUNKIE_PR_NUMBER
